### ISSUE TITLE
(-) ou neg: Indica número negativo

### ISSUE THREAD

**Issue by camsgoms** [vsnepoifpe/dinamica#10]
Esta função deve permitir ao usuário converter um número positivo em um número negativo.

**Especificações:**

**Entrada:** Um número positivo.
**Saída:** O mesmo número com o sinal de menos à frente, indicando que é negativo.
**Exemplo:** Se o número de entrada for 5, a função deve retornar -5.

**Comment by aguedamaiara** [comment]
DIFICULDADE : 3
